---
# ydbd dynamic nodes rolling restart

- name: YDB database nodes rolling restart
  include_tasks: "restart_dynamic.yml"
  delegate_to: "{{ item }}"
  with_items: "{{ groups['ydbd_dynamic'] }}"
  run_once: true
