# YDB configuration options and their values
# are described in documentaion https://ydb.tech/en/docs/deploy/configuration/config

# static erasure is the parameter that
# describes the fault tolerance mode of the
# cluster. See docs for more details https://ydb.tech/en/docs/deploy/configuration/config#domains-blob
static_erasure: mirror-3-dc
host_configs: # the list of available host configurations in the cluster.
- drive:
  - path: /dev/disk/by-partlabel/ydb_disk_1    # path of the first disk in the host configration.
    type: SSD                                       # kind of the disk: available kinds are SSD, NVME, HDD
  - path: /dev/disk/by-partlabel/ydb_disk_2
    type: SSD
  - path: /dev/disk/by-partlabel/ydb_disk_3
    type: SSD
  host_config_id: 1
hosts:
- host: ycydb-1       # storage node DNS name
  host_config_id: 1                 # numeric host configuration template identifier
  walle_location:                   # this parameter describes where host is located.
    body: 1                         # string representing a host serial number.
    data_center: 'zone-a'           # string representing the datacenter / availability zone where the host is located.
                                    # if cluster is deployed using mirror-3-dc fault tolerance mode, all hosts must be distributed
                                    # across 3 datacenters.
    rack: '1'                       # string representing a rack identifier where the host is located.
                                    # if cluster is deployed using block-4-2 erasure, all hosts should be distrubited
                                    # accross at least 8 racks.
- host: ycydb-2
  host_config_id: 1
  walle_location:
    body: 2
    data_center: 'zone-b'
    rack: '2'
- host: ycydb-3
  host_config_id: 1
  walle_location:
    body: 3
    data_center: 'zone-c'
    rack: '3'
domains_config:
  # There can be only one root domain in a cluster. Domain name prefixes all scheme objects names, e.g. full name of a table table1 in database db1.
  # in a cluster with domains_config.domain.name parameter set to Root would be equal to /Root/db1/table1
  domain:
  - name: Root
    storage_pool_types:
    - kind: ssd
      pool_config:
        box_id: 1
        # fault tolerance mode name - none, block-4-2, or mirror-3-dc..
        # See docs for more details https://ydb.tech/en/docs/deploy/configuration/config#domains-blob
        erasure_species: mirror-3-dc
        kind: ssd
        geometry:
          realm_level_begin: 10
          realm_level_end: 20
          domain_level_begin: 10
          domain_level_end: 256
        pdisk_filter:
        - property:
          - type: SSD  # device type to match host_configs.drive.type
        vdisk_kind: Default
  state_storage:
  - ring:
      node: [1, 2, 3]
      nto_select: 3
    ssid: 1
  security_config:
    enforce_user_token_requirement: true      # User 'root' with the empty password out of box
    monitoring_allowed_sids:
    - "root"
    - "ADMINS"
    - "DATABASE-ADMINS"
    administration_allowed_sids:
    - "root"
    - "ADMINS"
    - "DATABASE-ADMINS"
    viewer_allowed_sids:
    - "root"
    - "ADMINS"
    - "DATABASE-ADMINS"
table_service_config:
  sql_version: 1
actor_system_config:          # the configuration of the actor system which descibes how cores of the instance are distributed
  executor:                   # accross different types of workloads in the instance.
  - name: System              # system executor of the actor system. in this executor YDB launches system type of workloads, like system tablets
                              # and reads from storage.
    threads: 4                # the number of threads allocated to system executor.
    type: BASIC
  - name: User                # user executor of the actor system. In this executor YDB launches user workloads, like datashard activities,
                              # queries and rpc calls.
    threads: 8                # the number of threads allocated to user executor.
    type: BASIC
  - name: Batch               # user executor of the actor system. In this executor YDB launches batch operations, like scan queries, table
                              # compactions, background compactions.
    threads: 4                # the number of threads allocated to the batch executor.
    type: BASIC
  - name: IO                  # the io executor. In this executor launches sync operations and writes logs.
    threads: 2
    time_per_mailbox_micro_secs: 100
    type: IO
  - name: IC                  # the interconnect executor which YDB uses for network communications accross different nodes of the cluster.
    spin_threshold: 10
    threads: 4                # the number of threads allocated to the interconnect executor.
    time_per_mailbox_micro_secs: 100
    type: BASIC
  scheduler:
    progress_threshold: 10000
    resolution: 256
    spin_threshold: 0
blob_storage_config:         # configuration of static blobstorage group.
                             # YDB uses this group to store system tablets' data, like SchemeShard
  service_set:
    groups:
    - erasure_species: mirror-3-dc # fault tolerance mode name for the static group
      rings:          # in mirror-3-dc must have exactly 3 rings or availability zones
      - fail_domains:  # first record: fail domains of the static group describe where each vdisk of the static group should be located.
        - vdisk_locations:
          - node_id: ycydb-1
            pdisk_category: SSD
            path: /dev/disk/by-partlabel/ydb_disk_1
        - vdisk_locations:
          - node_id: ycydb-1
            pdisk_category: SSD
            path: /dev/disk/by-partlabel/ydb_disk_2
        - vdisk_locations:
          - node_id: ycydb-1
            pdisk_category: SSD
            path: /dev/disk/by-partlabel/ydb_disk_3
      - fail_domains: # second ring: fail domains of the static group describe where each vdisk of the static group should be located.
        - vdisk_locations:
          - node_id: ycydb-2
            pdisk_category: SSD
            path: /dev/disk/by-partlabel/ydb_disk_1
        - vdisk_locations:
          - node_id: ycydb-2
            pdisk_category: SSD
            path: /dev/disk/by-partlabel/ydb_disk_2
        - vdisk_locations:
          - node_id: ycydb-2
            pdisk_category: SSD
            path: /dev/disk/by-partlabel/ydb_disk_3
      - fail_domains: # third ring: fail domains of the static group describe where each vdisk of the static group should be located.
        - vdisk_locations:
          - node_id: ycydb-3
            pdisk_category: SSD
            path: /dev/disk/by-partlabel/ydb_disk_1
        - vdisk_locations:
          - node_id: ycydb-3
            pdisk_category: SSD
            path: /dev/disk/by-partlabel/ydb_disk_2
        - vdisk_locations:
          - node_id: ycydb-3
            pdisk_category: SSD
            path: /dev/disk/by-partlabel/ydb_disk_3
channel_profile_config:
  profile:
  - channel:
    - erasure_species: mirror-3-dc
      pdisk_category: 0
      storage_pool_kind: ssd
    - erasure_species: mirror-3-dc
      pdisk_category: 0
      storage_pool_kind: ssd
    - erasure_species: mirror-3-dc
      pdisk_category: 0
      storage_pool_kind: ssd
    profile_id: 0
