---
# ydbd static node configuration

- name: Copy static node configuration
  copy: src={{ ydbd_config_static }} dest={{ ydbd_dir }}/cfg/ydbd-static.yaml

- name: Copy the static node systemd service file
  copy: src=ydbd-storage.service dest=/etc/systemd/system/ydbd-storage.service

- name: Create the disk formatting script
  template: src=safe_format.j2 dest={{ ydbd_dir }}/home/safe_format.sh mode=755

- name: Create the static node startup wait script
  template: src=wait_static.j2 dest={{ ydbd_dir }}/home/wait_static.sh mode=755

- name: Create the storage initialization script
  template: src=init_storage.j2 dest={{ ydbd_dir }}/home/init_storage.sh mode=755

- name: Execute disk formatting
  command: "{{ ydbd_dir }}/home/safe_format.sh {{ item['name'] }} {{ item['label'] }}"
  with_items: "{{ ydbd_disks }}"

- name: Refresh systemd services configuration
  ansible.builtin.systemd:
    daemon_reload: true

- name: Start the storage node
  ansible.builtin.systemd:
    state: started
    name: ydbd-storage

- name: Wait for storage node startup
  command: "sudo -u ydb {{ ydbd_dir }}/home/wait_static.sh {{ inventory_hostname }}"

- name: Initialize the YDB storage
  command: "sudo -u ydb {{ ydbd_dir }}/home/init_storage.sh {{ inventory_hostname }}"
  run_once: true
