---
# ydbd static node configuration

- name: Copy static node configuration
  copy: src={{ ydbd_config_static }} dest={{ ydbd_dir }}/cfg/ydbd-static.yaml

- name: Create the disk formatting script
  template: src=safe_format.j2 dest={{ ydbd_dir }}/bin/safe_format.sh mode=755

- name: Execute disk formatting
  command: "{{ ydbd_dir }}/bin/safe_format.sh {{ item['name'] }} {{ item['label'] }} >>/tmp/safe_format.log 2>&1"
  with_items: "{{ ydbd_disks }}"
