global:
  scrape_interval: 15s
  scrape_timeout: 15s
  evaluation_interval: 15s

scrape_configs:
- job_name: ydb/ydb
  scheme: https
  tls_config:
    ca_file: '/home/demo/prometheus/config/ydb-ca.cer'
  metric_relabel_configs:
  - regex: (.*)
    replacement: ydb_$1
    source_labels:
    - __name__
    target_label: __name__
  metrics_path: /counters/counters=ydb/name_label=name/prometheus
  relabel_configs:
  - regex: ([^:]+)(:[0-9]+)?
    replacement: ${1}
    source_labels:
    - __address__
    target_label: instance
  - source_labels: 
    - __address__
    target_label: counter
    replacement: ydb
  file_sd_configs:
  - files:
    - "/home/demo/prometheus/config/ydbd-storage.yml"
    - "/home/demo/prometheus/config/ydbd-database-*.yml"

- job_name: ydb/auth
  scheme: https
  tls_config:
    ca_file: '/home/demo/prometheus/config/ydb-ca.cer'
  metric_relabel_configs:
  - regex: (.*)
    replacement: auth_$1
    source_labels:
    - __name__
    target_label: __name__
  metrics_path: /counters/counters=auth/prometheus
  relabel_configs:
  - regex: ([^:]+)(:[0-9]+)?
    replacement: ${1}
    source_labels:
    - __address__
    target_label: instance
  - source_labels: 
    - __address__
    target_label: counter
    replacement: auth
  file_sd_configs:
  - files:
    - "/home/demo/prometheus/config/ydbd-storage.yml"
    - "/home/demo/prometheus/config/ydbd-database-*.yml"

- job_name: ydb/coordinator
  scheme: https
  tls_config:
    ca_file: '/home/demo/prometheus/config/ydb-ca.cer'
  metric_relabel_configs:
  - regex: (.*)
    replacement: coordinator_$1
    source_labels:
    - __name__
    target_label: __name__
  metrics_path: /counters/counters=coordinator/prometheus
  relabel_configs:
  - regex: ([^:]+)(:[0-9]+)?
    replacement: ${1}
    source_labels:
    - __address__
    target_label: instance
  - source_labels: 
    - __address__
    target_label: counter
    replacement: coordinator
  file_sd_configs:
  - files:
    - "/home/demo/prometheus/config/ydbd-storage.yml"
    - "/home/demo/prometheus/config/ydbd-database-*.yml"

- job_name: ydb/dsproxy_queue
  scheme: https
  tls_config:
    ca_file: '/home/demo/prometheus/config/ydb-ca.cer'
  metric_relabel_configs:
  - regex: (.*)
    replacement: dsproxy_queue_$1
    source_labels:
    - __name__
    target_label: __name__
  metrics_path: /counters/counters=dsproxy_queue/prometheus
  relabel_configs:
  - regex: ([^:]+)(:[0-9]+)?
    replacement: ${1}
    source_labels:
    - __address__
    target_label: instance
  - source_labels: 
    - __address__
    target_label: counter
    replacement: dsproxy_queue
  file_sd_configs:
  - files:
    - "/home/demo/prometheus/config/ydbd-storage.yml"
    - "/home/demo/prometheus/config/ydbd-database-*.yml"

- job_name: ydb/dsproxy
  scheme: https
  tls_config:
    ca_file: '/home/demo/prometheus/config/ydb-ca.cer'
  metric_relabel_configs:
  - regex: (.*)
    replacement: dsproxy_$1
    source_labels:
    - __name__
    target_label: __name__
  metrics_path: /counters/counters=dsproxy/prometheus
  relabel_configs:
  - regex: ([^:]+)(:[0-9]+)?
    replacement: ${1}
    source_labels:
    - __address__
    target_label: instance
  - source_labels: 
    - __address__
    target_label: counter
    replacement: dsproxy
  file_sd_configs:
  - files:
    - "/home/demo/prometheus/config/ydbd-storage.yml"
    - "/home/demo/prometheus/config/ydbd-database-*.yml"

- job_name: ydb/dsproxy_percentile
  scheme: https
  tls_config:
    ca_file: '/home/demo/prometheus/config/ydb-ca.cer'
  metric_relabel_configs:
  - regex: (.*)
    replacement: dsproxy_percentile_$1
    source_labels:
    - __name__
    target_label: __name__
  metrics_path: /counters/counters=dsproxy_percentile/prometheus
  relabel_configs:
  - regex: ([^:]+)(:[0-9]+)?
    replacement: ${1}
    source_labels:
    - __address__
    target_label: instance
  - source_labels: 
    - __address__
    target_label: counter
    replacement: dsproxy_percentile
  file_sd_configs:
  - files:
    - "/home/demo/prometheus/config/ydbd-storage.yml"
    - "/home/demo/prometheus/config/ydbd-database-*.yml"

- job_name: ydb/grpc
  scheme: https
  tls_config:
    ca_file: '/home/demo/prometheus/config/ydb-ca.cer'
  metric_relabel_configs:
  - regex: (.*)
    replacement: grpc_$1
    source_labels:
    - __name__
    target_label: __name__
  metrics_path: /counters/counters=grpc/prometheus
  relabel_configs:
  - regex: ([^:]+)(:[0-9]+)?
    replacement: ${1}
    source_labels:
    - __address__
    target_label: instance
  - source_labels: 
    - __address__
    target_label: counter
    replacement: grpc
  file_sd_configs:
  - files:
    - "/home/demo/prometheus/config/ydbd-storage.yml"
    - "/home/demo/prometheus/config/ydbd-database-*.yml"

- job_name: ydb/kqp
  scheme: https
  tls_config:
    ca_file: '/home/demo/prometheus/config/ydb-ca.cer'
  metric_relabel_configs:
  - regex: (.*)
    replacement: kqp_$1
    source_labels:
    - __name__
    target_label: __name__
  metrics_path: /counters/counters=kqp/prometheus
  relabel_configs:
  - regex: ([^:]+)(:[0-9]+)?
    replacement: ${1}
    source_labels:
    - __address__
    target_label: instance
  - source_labels: 
    - __address__
    target_label: counter
    replacement: kqp
  file_sd_configs:
  - files:
    - "/home/demo/prometheus/config/ydbd-database-*.yml"

- job_name: ydb/processing
  scheme: https
  tls_config:
    ca_file: '/home/demo/prometheus/config/ydb-ca.cer'
  metric_relabel_configs:
  - regex: (.*)
    replacement: processing_$1
    source_labels:
    - __name__
    target_label: __name__
  metrics_path: /counters/counters=processing/prometheus
  relabel_configs:
  - regex: ([^:]+)(:[0-9]+)?
    replacement: ${1}
    source_labels:
    - __address__
    target_label: instance
  - source_labels: 
    - __address__
    target_label: counter
    replacement: processing
  file_sd_configs:
  - files:
    - "/home/demo/prometheus/config/ydbd-storage.yml"
    - "/home/demo/prometheus/config/ydbd-database-*.yml"

- job_name: ydb/proxy
  scheme: https
  tls_config:
    ca_file: '/home/demo/prometheus/config/ydb-ca.cer'
  metric_relabel_configs:
  - regex: (.*)
    replacement: proxy_$1
    source_labels:
    - __name__
    target_label: __name__
  metrics_path: /counters/counters=proxy/prometheus
  relabel_configs:
  - regex: ([^:]+)(:[0-9]+)?
    replacement: ${1}
    source_labels:
    - __address__
    target_label: instance
  - source_labels: 
    - __address__
    target_label: counter
    replacement: proxy
  file_sd_configs:
  - files:
    - "/home/demo/prometheus/config/ydbd-storage.yml"
    - "/home/demo/prometheus/config/ydbd-database-*.yml"

- job_name: ydb/followers
  scheme: https
  tls_config:
    ca_file: '/home/demo/prometheus/config/ydb-ca.cer'
  metric_relabel_configs:
  - regex: (.*)
    replacement: followers_$1
    source_labels:
    - __name__
    target_label: __name__
  metrics_path: /counters/counters=followers/prometheus
  relabel_configs:
  - regex: ([^:]+)(:[0-9]+)?
    replacement: ${1}
    source_labels:
    - __address__
    target_label: instance
  - source_labels: 
    - __address__
    target_label: counter
    replacement: followers
  file_sd_configs:
  - files:
    - "/home/demo/prometheus/config/ydbd-storage.yml"
    - "/home/demo/prometheus/config/ydbd-database-*.yml"

- job_name: ydb/storage_pool_stat
  scheme: https
  tls_config:
    ca_file: '/home/demo/prometheus/config/ydb-ca.cer'
  metric_relabel_configs:
  - regex: (.*)
    replacement: storage_pool_stat_$1
    source_labels:
    - __name__
    target_label: __name__
  metrics_path: /counters/counters=storage_pool_stat/prometheus
  relabel_configs:
  - regex: ([^:]+)(:[0-9]+)?
    replacement: ${1}
    source_labels:
    - __address__
    target_label: instance
  - source_labels: 
    - __address__
    target_label: counter
    replacement: storage_pool_stat
  file_sd_configs:
  - files:
    - "/home/demo/prometheus/config/ydbd-storage.yml"
    - "/home/demo/prometheus/config/ydbd-database-*.yml"

- job_name: ydb/tablets
  scheme: https
  tls_config:
    ca_file: '/home/demo/prometheus/config/ydb-ca.cer'
  metric_relabel_configs:
  - regex: (.*)
    replacement: tablets_$1
    source_labels:
    - __name__
    target_label: __name__
  metrics_path: /counters/counters=tablets/prometheus
  relabel_configs:
  - regex: ([^:]+)(:[0-9]+)?
    replacement: ${1}
    source_labels:
    - __address__
    target_label: instance
  - source_labels: 
    - __address__
    target_label: counter
    replacement: tablets
  file_sd_configs:
  - files:
    - "/home/demo/prometheus/config/ydbd-storage.yml"
    - "/home/demo/prometheus/config/ydbd-database-*.yml"

- job_name: ydb/utils
  scheme: https
  tls_config:
    ca_file: '/home/demo/prometheus/config/ydb-ca.cer'
  metric_relabel_configs:
  - regex: (.*)
    replacement: utils_$1
    source_labels:
    - __name__
    target_label: __name__
  metrics_path: /counters/counters=utils/prometheus
  relabel_configs:
  - regex: ([^:]+)(:[0-9]+)?
    replacement: ${1}
    source_labels:
    - __address__
    target_label: instance
  - source_labels: 
    - __address__
    target_label: counter
    replacement: utils
  file_sd_configs:
  - files:
    - "/home/demo/prometheus/config/ydbd-storage.yml"
    - "/home/demo/prometheus/config/ydbd-database-*.yml"

- job_name: ydb/dsproxynode
  scheme: https
  tls_config:
    ca_file: '/home/demo/prometheus/config/ydb-ca.cer'
  metric_relabel_configs:
  - regex: (.*)
    replacement: dsproxynode_$1
    source_labels:
    - __name__
    target_label: __name__
  metrics_path: /counters/counters=dsproxynode/prometheus
  relabel_configs:
  - regex: ([^:]+)(:[0-9]+)?
    replacement: ${1}
    source_labels:
    - __address__
    target_label: instance
  - source_labels: 
    - __address__
    target_label: counter
    replacement: dsproxynode
  file_sd_configs:
  - files:
    - "/home/demo/prometheus/config/ydbd-storage.yml"
    - "/home/demo/prometheus/config/ydbd-database-*.yml"

- job_name: ydb/interconnect
  scheme: https
  tls_config:
    ca_file: '/home/demo/prometheus/config/ydb-ca.cer'
  metric_relabel_configs:
  - regex: (.*)
    replacement: interconnect_$1
    source_labels:
    - __name__
    target_label: __name__
  metrics_path: /counters/counters=interconnect/prometheus
  relabel_configs:
  - regex: ([^:]+)(:[0-9]+)?
    replacement: ${1}
    source_labels:
    - __address__
    target_label: instance
  - source_labels: 
    - __address__
    target_label: counter
    replacement: interconnect
  file_sd_configs:
  - files:
    - "/home/demo/prometheus/config/ydbd-storage.yml"
    - "/home/demo/prometheus/config/ydbd-database-*.yml"

- job_name: ydb/pdisks
  scheme: https
  tls_config:
    ca_file: '/home/demo/prometheus/config/ydb-ca.cer'
  metric_relabel_configs:
  - regex: (.*)
    replacement: pdisks_$1
    source_labels:
    - __name__
    target_label: __name__
  metrics_path: /counters/counters=pdisks/prometheus
  relabel_configs:
  - regex: ([^:]+)(:[0-9]+)?
    replacement: ${1}
    source_labels:
    - __address__
    target_label: instance
  - source_labels: 
    - __address__
    target_label: counter
    replacement: pdisks
  file_sd_configs:
  - files:
    - "/home/demo/prometheus/config/ydbd-storage.yml"

- job_name: ydb/vdisks
  scheme: https
  tls_config:
    ca_file: '/home/demo/prometheus/config/ydb-ca.cer'
  metric_relabel_configs:
  - regex: (.*)
    replacement: vdisks_$1
    source_labels:
    - __name__
    target_label: __name__
  metrics_path: /counters/counters=vdisks/prometheus
  relabel_configs:
  - regex: ([^:]+)(:[0-9]+)?
    replacement: ${1}
    source_labels:
    - __address__
    target_label: instance
  - source_labels: 
    - __address__
    target_label: counter
    replacement: vdisks
  file_sd_configs:
  - files:
    - "/home/demo/prometheus/config/ydbd-storage.yml"

- job_name: ydb/healthcheck
  scheme: https
  tls_config:
    ca_file: '/home/demo/prometheus/config/ydb-ca.cer'
  metrics_path: /healthcheck
  params:
    format:
    - prometheus
  relabel_configs:
  - regex: ([^:]+)(:[0-9]+)?
    replacement: ${1}
    source_labels:
    - __address__
    target_label: instance
  - source_labels: 
    - __address__
    target_label: counter
    replacement: healthcheck
  file_sd_configs:
  - files:
    - "/home/demo/prometheus/config/ydbd-storage.yml"
    - "/home/demo/prometheus/config/ydbd-database-*.yml"
