apiVersion: 1
deleteDatasources: []

datasources:
  - name: default
    type: prometheus
    orgId: 1
    access: proxy
    url: http://localhost:9090
    isDefault: true
    editable: false
    jsonData:
      prometheusType: Prometheus

