global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "ydb_dynamic"
    metrics_path: "/counters/counters=ydb/name_label=name/prometheus"
    scheme: https
    tls_config:
      ca_file: "/home/demo/ca.crt"
    basic_auth:
      username: stroppy
      password: $2y$10$4kt5ymMbEq5m6AUeaa90xufYAFS8x9.9tNqLKuufrF9ksqkoAhNMi
    static_configs:
      - targets: ["ycydb-s1:8766","ycydb-s2:8766","ycydb-s3:8766","ycydb-s4:8766","ycydb-s5:8766","ycydb-s6:8766","ycydb-s7:8766","ycydb-s8:8766","ycydb-s9:8766","ycydb-s10:8766","ycydb-s11:8766","ycydb-s12:8766","ycydb-s13:8766","ycydb-s14:8766","ycydb-s15:8766","ycydb-s16:8766","ycydb-s17:8766","ycydb-s18:8766"]
        labels:
          container: ydb-dynamic
    metric_relabel_configs:
      - source_labels: ["__name__"]
        target_label: "__name__"
        replacement: "ydb_$1"
  - job_name: "utils_dynamic"
    metrics_path: "/counters/counters=utils/prometheus"
    scheme: https
    tls_config:
      ca_file: "/home/demo/ca.crt"
    basic_auth:
      username: stroppy
      password: $2y$10$4kt5ymMbEq5m6AUeaa90xufYAFS8x9.9tNqLKuufrF9ksqkoAhNMi
    static_configs:
      - targets: ["ycydb-s1:8766","ycydb-s2:8766","ycydb-s3:8766","ycydb-s4:8766","ycydb-s5:8766","ycydb-s6:8766","ycydb-s7:8766","ycydb-s8:8766","ycydb-s9:8766","ycydb-s10:8766","ycydb-s11:8766","ycydb-s12:8766","ycydb-s13:8766","ycydb-s14:8766","ycydb-s15:8766","ycydb-s16:8766","ycydb-s17:8766","ycydb-s18:8766"]
        labels:
          container: ydb-dynamic
    metric_relabel_configs:
      - source_labels: ["__name__"]
        target_label: "__name__"
        replacement: "utils_$1"
  - job_name: "kqp_dynamic"
    metrics_path: "/counters/counters=kqp/prometheus"
    scheme: https
    tls_config:
      ca_file: "/home/demo/ca.crt"
    basic_auth:
      username: stroppy
      password: $2y$10$4kt5ymMbEq5m6AUeaa90xufYAFS8x9.9tNqLKuufrF9ksqkoAhNMi
    static_configs:
      - targets: ["ycydb-s1:8766","ycydb-s2:8766","ycydb-s3:8766","ycydb-s4:8766","ycydb-s5:8766","ycydb-s6:8766","ycydb-s7:8766","ycydb-s8:8766","ycydb-s9:8766","ycydb-s10:8766","ycydb-s11:8766","ycydb-s12:8766","ycydb-s13:8766","ycydb-s14:8766","ycydb-s15:8766","ycydb-s16:8766","ycydb-s17:8766","ycydb-s18:8766"]
        labels:
          container: ydb-dynamic
    metric_relabel_configs:
      - source_labels: ["__name__"]
        target_label: "__name__"
        replacement: "kqp_$1"
  - job_name: "tablets_dynamic"
    metrics_path: "/counters/counters=tablets/prometheus"
    scheme: https
    tls_config:
      ca_file: "/home/demo/ca.crt"
    basic_auth:
      username: stroppy
      password: $2y$10$4kt5ymMbEq5m6AUeaa90xufYAFS8x9.9tNqLKuufrF9ksqkoAhNMi
    static_configs:
      - targets: ["ycydb-s1:8766","ycydb-s2:8766","ycydb-s3:8766","ycydb-s4:8766","ycydb-s5:8766","ycydb-s6:8766","ycydb-s7:8766","ycydb-s8:8766","ycydb-s9:8766","ycydb-s10:8766","ycydb-s11:8766","ycydb-s12:8766","ycydb-s13:8766","ycydb-s14:8766","ycydb-s15:8766","ycydb-s16:8766","ycydb-s17:8766","ycydb-s18:8766"]
        labels:
          container: ydb-dynamic
    metric_relabel_configs:
      - source_labels: ["__name__"]
        target_label: "__name__"
        replacement: "tablets_$1"
  - job_name: "proxy_dynamic"
    metrics_path: "/counters/counters=proxy/prometheus"
    scheme: https
    tls_config:
      ca_file: "/home/demo/ca.crt"
    basic_auth:
      username: stroppy
      password: $2y$10$4kt5ymMbEq5m6AUeaa90xufYAFS8x9.9tNqLKuufrF9ksqkoAhNMi
    static_configs:
      - targets: ["ycydb-s1:8766","ycydb-s2:8766","ycydb-s3:8766","ycydb-s4:8766","ycydb-s5:8766","ycydb-s6:8766","ycydb-s7:8766","ycydb-s8:8766","ycydb-s9:8766","ycydb-s10:8766","ycydb-s11:8766","ycydb-s12:8766","ycydb-s13:8766","ycydb-s14:8766","ycydb-s15:8766","ycydb-s16:8766","ycydb-s17:8766","ycydb-s18:8766"]
        labels:
          container: ydb-dynamic
    metric_relabel_configs:
      - source_labels: ["__name__"]
        target_label: "__name__"
        replacement: "proxy_$1"
  - job_name: "dsproxynode_dynamic"
    metrics_path: "/counters/counters=dsproxynode/prometheus"
    scheme: https
    tls_config:
      ca_file: "/home/demo/ca.crt"
    basic_auth:
      username: stroppy
      password: $2y$10$4kt5ymMbEq5m6AUeaa90xufYAFS8x9.9tNqLKuufrF9ksqkoAhNMi
    static_configs:
      - targets: ["ycydb-s1:8766","ycydb-s2:8766","ycydb-s3:8766","ycydb-s4:8766","ycydb-s5:8766","ycydb-s6:8766","ycydb-s7:8766","ycydb-s8:8766","ycydb-s9:8766","ycydb-s10:8766","ycydb-s11:8766","ycydb-s12:8766","ycydb-s13:8766","ycydb-s14:8766","ycydb-s15:8766","ycydb-s16:8766","ycydb-s17:8766","ycydb-s18:8766"]
        labels:
          container: ydb-dynamic
    metric_relabel_configs:
      - source_labels: ["__name__"]
        target_label: "__name__"
        replacement: "dsproxynode_$1"
  - job_name: "ic_dynamic"
    metrics_path: "/counters/counters=interconnect/prometheus"
    scheme: https
    tls_config:
      ca_file: "/home/demo/ca.crt"
    basic_auth:
      username: stroppy
      password: $2y$10$4kt5ymMbEq5m6AUeaa90xufYAFS8x9.9tNqLKuufrF9ksqkoAhNMi
    static_configs:
      - targets: ["ycydb-s1:8766","ycydb-s2:8766","ycydb-s3:8766","ycydb-s4:8766","ycydb-s5:8766","ycydb-s6:8766","ycydb-s7:8766","ycydb-s8:8766","ycydb-s9:8766","ycydb-s10:8766","ycydb-s11:8766","ycydb-s12:8766","ycydb-s13:8766","ycydb-s14:8766","ycydb-s15:8766","ycydb-s16:8766","ycydb-s17:8766","ycydb-s18:8766"]
        labels:
          container: ydb-dynamic
    metric_relabel_configs:
      - source_labels: ["__name__"]
        target_label: "__name__"
        replacement: "interconnect_$1"
