static_erasure: none
host_configs:
- drive:
  - path: /dev/disk/by-partlabel/pig-drive
    type: SSD
  host_config_id: 1
hosts:
- host: localhost
  host_config_id: 1
  port: 19001
  walle_location:
    body: 1
    data_center: '1'
    rack: '1'
domains_config:
  domain:
  - name: Root
    storage_pool_types:
    - kind: ssd
      pool_config:
        box_id: 1
        erasure_species: none
        kind: ssd
        pdisk_filter:
        - property:
          - type: SSD
        vdisk_kind: Default
  state_storage:
  - ring:
      node:
      - 1
      nto_select: 1
    ssid: 1
actor_system_config:
  executor:
  - {name: System, spin_threshold: '10', threads: 2, max_threads: 11, type: BASIC}
  - {name: User, spin_threshold: '1', threads: 7, max_threads: 12, type: BASIC}
  - {name: Batch, spin_threshold: '1', threads: 2, max_threads: 4, type: BASIC}
  - {name: IO, threads: 1, type: IO}
  - {name: IC, spin_threshold: '10', threads: 3, max_threads: 11, time_per_mailbox_micro_secs: 100, max_avg_ping_deviation: 500, type: BASIC}
  scheduler: {progress_threshold: '10000', resolution: '64', spin_threshold: '0'}
  sys_executor: 0
  user_executor: 1
  batch_executor: 2
  io_executor: 3
  service_executor:
  - {executor_id: 4, service_name: Interconnect}

blob_storage_config:
  service_set:
    groups:
    - erasure_species: none
      rings:
      - fail_domains:
        - vdisk_locations:
          - node_id: 1
            path: /dev/disk/by-partlabel/pig-drive
            pdisk_category: SSD

channel_profile_config:
  profile:
  - channel:
    - erasure_species: none
      pdisk_category: 0
      storage_pool_kind: ssd
    - erasure_species: none
      pdisk_category: 0
      storage_pool_kind: ssd
    - erasure_species: none
      pdisk_category: 0
      storage_pool_kind: ssd
    profile_id: 0

table_service_config:
  sql_version: 1
  enable_kqp_scan_query_source_read: true
  enable_kqp_data_query_source_read: true
  enable_kqp_data_query_stream_lookup: true
  enable_kqp_scan_query_stream_lookup: true
  enable_kqp_immediate_effects: true
  enable_sequential_reads: true

grpc_config:
  host: 127.0.0.1
  worker_threads: 2
  workers_per_completion_queue: 1
  handlers_per_completion_queue: 1000
  grpc_proxy_count: 2

shared_cache_config:
  memory_limit: 17179869184

monitoring_config:
  monitoring_address: 127.0.0.1

