---
# ydbd dynamic node deployment

- name: Generate the dynamic node services files
  template:
    src: dynnode-service.j2
    dest: "/etc/systemd/system/ydbd-{{ item.dbname }}-{{ item.instance }}.service"
  loop: "{{ ydbd_dynnodes }}"
