---
# ydbd rolling restart

- name: Start the storage node
  ansible.builtin.systemd:
    state: started
    name: ydbd-storage

- name: Wait for storage node startup
  command: "sudo -u ydb {{ ydbd_dir }}/home/wait_static.sh {{ inventory_hostname }}"
